# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
