# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20170425_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('score_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Person')),
            ],
        ),
    ]
