# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_categoryscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryscore',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
